### ISSUE TITLE
Ответ резолвера на адрес из заблокированного списка.

### ISSUE THREAD

**Issue by Afafka** [ufm/yggdns64#1]
Программа прекрасно работает, спасибо.
Однако,  при использовании форвардера с фильтрацией контента , например AdGuard, резолвер выдаёт ответ вида [prefix ::] , что в свою очередь генерирует паразитный трафик и замедляет работу всей системы.

Возможно ли добавить исключение при преобразованиях резольвера для адресов вида 0.0.0.0 и [::] так , что-бы он выдавал их в исходном виде?

**Comment by ufm** [comment]
Эммм...
Правильно ли я понял просьбу:
1. В случае получения адреса 0.0.0.0 переделываеть его в вид [::]
2. В случае получения адреса [::] - возвращать его как есть
?

**Comment by Afafka** [comment]
Всё верно.

**Comment by ufm** [comment]
Добавлено в конфиг
invalid-address: process

**Comment by Afafka** [comment]
Спасибо
